SET (CMAKE_SYSTEM_NAME Linux)
SET (CMAKE_SYSTEM_VERSION Android)

SET (TOOCHAIN ../toolchain/sysroot)

SET (CMAKE_C_COMPILER /usr/bin/gcc)
SET (CMAKE_CXX_COMPILER /usr/bin/g++)
SET (CMAKE_FIND_ROOT_PATH $TOOCHAIN/sysroot)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
