SET (CMAKE_SYSTEM_NAME Linux)
SET (CMAKE_SYSTEM_VERSION Android)

SET (TOOLCHAIN ${CMAKE_CURRENT_LIST_DIR}/toolchain)

SET (CMAKE_C_COMPILER ${TOOLCHAIN}/bin/arm-linux-androideabi-gcc)
SET (CMAKE_CXX_COMPILER ${TOOLCHAIN}/bin/arm-linux-androideabi-g++)
SET (CMAKE_FIND_ROOT_PATH ${TOOLCHAIN}/sysroot)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
